import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import path from 'node:path';
import { spawn } from 'node:child_process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Dev-only plugin: after successful rebuild, copy artifacts into release/ and run installer
const devInstallPlugin = {
  name: 'dev-install',
  setup(build) {
    const cwd = process.cwd();
    const buildScript = path.join(cwd, 'scripts', 'build.js');
    const installer = path.join(cwd, 'scripts', 'install.js');

    let installing = false;
    let rerunPending = false;

    function runTasks() {
      if (installing) {
        rerunPending = true;
        return;
      }
      installing = true;
      // Step 1: build Dev artifacts into build/dev
      const b = spawn(process.execPath, [buildScript, 'Dev'], { stdio: 'inherit' });
      b.on('error', (err) => {
        installing = false;
        console.error('[dev-install] build failed to start:', err);
      });
      b.on('exit', (code) => {
        if (code && code !== 0) {
          installing = false;
          console.error(`[dev-install] build exited with code ${code}`);
          return;
        }
        // Step 2: install from build/dev
        const i = spawn(process.execPath, [installer, 'Dev'], { stdio: 'inherit' });
        i.on('error', (err) => {
          installing = false;
          console.error('[dev-install] installer failed to start:', err);
        });
        i.on('exit', () => {
          installing = false;
          if (rerunPending) {
            rerunPending = false;
            runTasks();
          }
        });
      });
    }

    build.onEnd((result) => {
      if (result.errors && result.errors.length > 0) return;
      if (prod) return;
      runTasks();
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: prod ? [] : [devInstallPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
